# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ROsSluiTaBqxOVo0Gc6U82cHxWRCNUeH
"""

import pandas as pd
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

modelo = LinearSVC()

table = 'tracking.csv'
dados = pd.read_csv(table)
dados

x = dados[['home', 'how_it_works', 'contact']]
y = dados[['bought']]
print(y)

dados.shape

treino_x, teste_x, treino_y, teste_y = train_test_split(x, y, test_size = 0.25, random_state=20, stratify=y)
print("Treinaremos com %d elementos e testaremos com %d elementos" % (len(treino_x), len(teste_x)))

modelo.fit(treino_x, treino_y)
previsoes = modelo.predict(teste_x)

accurracy = accuracy_score(teste_y, previsoes) * 100
print("A acurácia foi %.2f%%" % accurracy)

treino_y.value_counts()

teste_y.value_counts()

